# nohup ./run.sh > run.log 2>&1 &
# python main.py --config "configs/gat/split1/config_jk1_pooling1.json"
# python main.py --config "configs/gat/split1/config_jk1_pooling2.json"
# python main.py --config "configs/gat/split1/config_jk1_pooling3.json"
# python main.py --config "configs/gat/split1/config_jk2_pooling1.json"
# python main.py --config "configs/gat/split1/config_jk2_pooling2.json"
# python main.py --config "configs/gat/split1/config_jk2_pooling3.json"
# python main.py --config "configs/gat/split2/config_jk1_pooling1.json"
# python main.py --config "configs/gat/split2/config_jk1_pooling2.json"
# python main.py --config "configs/gat/split2/config_jk1_pooling3.json"
# python main.py --config "configs/gat/split2/config_jk2_pooling1.json"
# python main.py --config "configs/gat/split2/config_jk2_pooling2.json"
# python main.py --config "configs/gat/split2/config_jk2_pooling3.json"
#
# adaCAD
python main.py --config "configs/adaCAD/split2/kstep4_beta0.8_embdim100/config_jk1_pooling1.json"
python main.py --config "configs/adaCAD/split2/kstep4_beta0.8_embdim100/config_jk1_pooling2.json"
python main.py --config "configs/adaCAD/split2/kstep4_beta0.8_embdim100/config_jk1_pooling3.json"
python main.py --config "configs/adaCAD/split2/kstep4_beta0.8_embdim100/config_jk2_pooling1.json"
python main.py --config "configs/adaCAD/split2/kstep4_beta0.8_embdim100/config_jk2_pooling2.json"
python main.py --config "configs/adaCAD/split2/kstep4_beta0.8_embdim100/config_jk2_pooling3.json"
# split1
python main.py --config "configs/adaCAD/split1/kstep4_beta0.8_embdim100/config_jk1_pooling1.json"
python main.py --config "configs/adaCAD/split1/kstep4_beta0.8_embdim100/config_jk1_pooling2.json"
python main.py --config "configs/adaCAD/split1/kstep4_beta0.8_embdim100/config_jk1_pooling3.json"
python main.py --config "configs/adaCAD/split1/kstep4_beta0.8_embdim100/config_jk2_pooling1.json"
python main.py --config "configs/adaCAD/split1/kstep4_beta0.8_embdim100/config_jk2_pooling2.json"
python main.py --config "configs/adaCAD/split1/kstep4_beta0.8_embdim100/config_jk2_pooling3.json"
#
# adaCAD
python main.py --config "configs/adaCAD/split2/vary_ksteps/config_step1.json"
python main.py --config "configs/adaCAD/split2/vary_ksteps/config_step2.json"
python main.py --config "configs/adaCAD/split2/vary_ksteps/config_step3.json"
python main.py --config "configs/adaCAD/split2/vary_ksteps/config_step4.json"
python main.py --config "configs/adaCAD/split2/vary_ksteps/config_step5.json"
python main.py --config "configs/adaCAD/split2/vary_ksteps/config_step6.json"
python main.py --config "configs/adaCAD/split2/vary_ksteps/config_step7.json"
python main.py --config "configs/adaCAD/split2/vary_ksteps/config_step8.json"
python main.py --config "configs/adaCAD/split2/vary_ksteps/config_step9.json"
python main.py --config "configs/adaCAD/split2/vary_ksteps/config_step10.json"
python main.py --config "configs/adaCAD/split2/vary_ksteps/config_step0.json"